;; From Agha 1986, p. 52
(letrec ((stack-node (actor "stack-node" (content link)
                            (pop (customer)
                                 (if link
                                     (begin
                                       (send customer message content)
                                       (link))
                                     (begin
                                       (error "popping an empty stack")
                                       (terminate))))
                            (assertEmpty () (if link (error "not empty")
                                                     (become stack-node content link)))
                            (push (v)
                                  (become stack-node v (lambda () (become stack-node content link))))))
         (display-actor (actor "display" ()
                               (message (v) (display v) (become display-actor))))
         (act (create stack-node #f #f))
         (program-actor (actor "program" ()
                               (start ()
                                  (send act push (int-top))
                                  (send act pop disp)
                                  (send act assertEmpty))))
         (program2-actor (actor "program2" ()
                                (start ()
                                    (send (create program-actor) start))))
         (bootstrap-actor (actor "bootstrap" ()
                                 (start ()
                                    (send (create program2-actor) start))))
         (disp (create display-actor)))

  (send (create bootstrap-actor) start)
  (send (create bootstrap-actor) start))
